### ISSUE TITLE
Ordering too many donuts causes the checkout modal to overflow

### ISSUE THREAD

**Issue by kurtwacker** [CSC307Fall2019/Group-2#43]
<img width="986" alt="Screen Shot 2019-11-22 at 2 47 40 PM" src="https://user-images.githubusercontent.com/26883344/69465811-0d8e1880-0d37-11ea-8117-ef50308e05d3.png">

**Comment by theowatkins** [comment]
Added scrolling functionality in employee-order-checkout branch
